name: "Check YAML"

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  check-yaml-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:longsleep/golang-backports
          sudo apt update
          sudo apt install just yq golang-go

      - name: Check format
        run: |
          just check-ci
